package com.teaplantation.demo.mapper;

import com.teaplantation.demo.entity.Locus;

public interface LocusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locus
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locus
     *
     * @mbg.generated
     */
    int insert(Locus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locus
     *
     * @mbg.generated
     */
    int insertSelective(Locus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locus
     *
     * @mbg.generated
     */
    Locus selectByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locus
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Locus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locus
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Locus record);
}