package com.teaplantation.demo.entity;

import java.util.Date;

public class Locus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locus.lid
     *
     * @mbg.generated
     */
    private Long lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locus.locus_name
     *
     * @mbg.generated
     */
    private String locusName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locus.locus_temperature
     *
     * @mbg.generated
     */
    private Integer locusTemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locus.locus_humidity
     *
     * @mbg.generated
     */
    private Integer locusHumidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locus.locus_ph
     *
     * @mbg.generated
     */
    private Float locusPh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locus.upload_time
     *
     * @mbg.generated
     */
    private Date uploadTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locus.lid
     *
     * @return the value of locus.lid
     *
     * @mbg.generated
     */
    public Long getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locus.lid
     *
     * @param lid the value for locus.lid
     *
     * @mbg.generated
     */
    public void setLid(Long lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locus.locus_name
     *
     * @return the value of locus.locus_name
     *
     * @mbg.generated
     */
    public String getLocusName() {
        return locusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locus.locus_name
     *
     * @param locusName the value for locus.locus_name
     *
     * @mbg.generated
     */
    public void setLocusName(String locusName) {
        this.locusName = locusName == null ? null : locusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locus.locus_temperature
     *
     * @return the value of locus.locus_temperature
     *
     * @mbg.generated
     */
    public Integer getLocusTemperature() {
        return locusTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locus.locus_temperature
     *
     * @param locusTemperature the value for locus.locus_temperature
     *
     * @mbg.generated
     */
    public void setLocusTemperature(Integer locusTemperature) {
        this.locusTemperature = locusTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locus.locus_humidity
     *
     * @return the value of locus.locus_humidity
     *
     * @mbg.generated
     */
    public Integer getLocusHumidity() {
        return locusHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locus.locus_humidity
     *
     * @param locusHumidity the value for locus.locus_humidity
     *
     * @mbg.generated
     */
    public void setLocusHumidity(Integer locusHumidity) {
        this.locusHumidity = locusHumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locus.locus_ph
     *
     * @return the value of locus.locus_ph
     *
     * @mbg.generated
     */
    public Float getLocusPh() {
        return locusPh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locus.locus_ph
     *
     * @param locusPh the value for locus.locus_ph
     *
     * @mbg.generated
     */
    public void setLocusPh(Float locusPh) {
        this.locusPh = locusPh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locus.upload_time
     *
     * @return the value of locus.upload_time
     *
     * @mbg.generated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locus.upload_time
     *
     * @param uploadTime the value for locus.upload_time
     *
     * @mbg.generated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }
}